version = 0.1
[default.deploy.parameters]
stack_name = "bc-to-monday-webhook-test"
resolve_s3 = true
s3_prefix = "bc-to-monday-webhook-test"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
